apiVersion: v1
kind: Service
metadata:
  name: quarkus-rest-api-couchdb
  labels:
    app: quarkus-rest-api-couchdb
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: quarkus-rest-api-couchdb
---